name = "LatentDiffEq"
uuid = "5e00f16f-4024-4869-80ca-bd64fdfff9b1"
authors = ["Germ√°n Abrevaya <gabrevaya@df.uba.ar> and contributors"]
version = "0.2.1"

[deps]
DiffEqFlux = "aae7a2af-3d4f-5e19-a356-7da93b79d9d0"
DiffEqSensitivity = "41bf760c-e81c-5289-8e54-58b1f1f8abe2"
DynamicalSystems = "61744808-ddfa-5f27-97ff-6e42cc95d634"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StochasticDiffEq = "789caeaf-c7a9-5a7d-9973-96adeb23e2a0"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
